POST http://localhost:3001/authors
Content-Type: application/json

{
  "nome": "Luca",
  "cognome": "Verdi",
  "email": "lucaverdi@example.com",
  "dataDiNascita": "1990-03-01",
  "avatar": "https://i.pravatar.cc/150?img=3"
}


###
DELETE http://localhost:3001/authors/all

###
POST http://localhost:3001/api/create-admin
Content-Type: application/json

{
 
  "nome": "Fabio",
  "email": "fabio.mallardo16@gmail.com",
  "password": "Fabio2001"

}

###
GET http://localhost:3001/authors?page=1&limit=10


###
GET http://localhost:3001/blogPosts
